import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider } from "../hooks/authcontext";
import { TagsProvider } from "../hooks/tagsContext";

import "@blocknote/core/fonts/inter.css";
import "@blocknote/mantine/style.css";
import "@liveblocks/react-ui/styles.css";
import "@liveblocks/react-ui/styles/dark/media-query.css";
import "@liveblocks/react-tiptap/styles.css";
import ThemeProvider from "../components/ThemeProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <AuthProvider>
            <TagsProvider>
                <html lang="en" suppressHydrationWarning>
                    <body
                        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="system"
                            enableSystem>
                            {children}
                        </ThemeProvider>
                    </body>
                </html>
            </TagsProvider>
        </AuthProvider>
    );
}
